#cloud-config
package_upgrade: true
packages:
  - tmux
  - nmap
  - curl
  - wget
  - git
  - htop
  - iperf3
  - fail2ban
  - qemu-guest-agent
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXWn+gOcs0Qjb04yYge6vJbY6vejzoOvwLGX8x1zkmwBxB2WFaAubwj8If9Y2iSYkDMbxGWNkO63e8jyUhmhSpNhIsQlU4twhSrNZLBpQxLBon9eRN7oh0cU+W7lL7POCYMlYqgQuNJpMdU4wrOuRijLz98GSl6vA48UQa5y0efCvnXKUegR3uPxmtpr8E/nD5L8vSCM8DteCfi1dV7v9NhmcxNwK38MV0IiWB9d1hYYrZbZ80LOmHybnwHY1zs0oqy2/lyG0CuRQzsy7AdhDb7wEz1p+QksE96KAlMjDc9fjqZEwyd/Vurro/2JBRcDkb8FLS0FkgJR40IFOA3dotoIcXZe2tuaEkiFbuzEoKAQz9g5Iqdi8wnsjcI8ld598Yu6svjIDVjpec1+SG3Ipi01miGS1cqLt2n247FoyFPN2VENTEuKY4GGnsyoTXGpd35Oly+XaUyHUG599bpjXbRILA941I5hJSXoFij5eyXfg45YB5Og+xNqifraDsyeWRE51yz0+zJKNN40sOubpMjTMjekrTHgW7un9x9F+svmfQ8dQg0oyc6j8U+Hsna+htr1PAVpJ0KwG1H0HjJ03dXMV+2ixuu6J9H5nImGsxqgllqfi4Cf6amamg397IsnoAZmM02EjJpfjbpFEHdmKAq0R+t+/VekBkJkEERO0cFw== Client@VM
runcmd:
  - sudo systemctl start qemu-guest-agent
  - sudo systemctl enable qemu-guest-agent
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
  - sed -i 's|UsePAM yes|UsePAM no|g' /etc/ssh/sshd_config
  - restart ssh
final_message: "The system is finally up, after $UPTIME seconds"
# cloud-init logs: /var/log/cloud-init.log and /var/log/cloud-init-output.log