#cloud-config
package_upgrade: true
packages:
  - nmap
  - curl
  - wget
  - git
  - htop
  - iperf3
  - fail2ban
  - qemu-guest-agent
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMsWy4xtV23AVHwNSZKokocJjBJQkZ6GtFKNfh5BWbfG48b0BwNS+i5fKReXOdTS1kyI+NWCZxT+9eLbF+w7dsqj1ArsZP96so22slPCv+hRmj1a84cDiglXXMzC2DuYx9Qz2q4tUWoM/GQGWrqqF/abS9QG1/a3SGg+KgCIR2gP2Iakvb/zPKKUV3CfSEm1tibu34T1+aZVjypcoFfDDDNz0eU5FBD/1puWVImZ28k8gOnFSz5Hw6Rvr/XpQW5uLj6T8bNYmMxf8hn40qzH7dQgUbP3KJVbEGTmKlREKEIFJfQyryRdYjBgA08mQo9XFNu4zcI9ruwdVYB6C9dRCFYBBwii3ddMhuhbBk5vbOdVTi1ODIT0ncFsRmtKoNYNhwMl6NZXOePxXbbj4hJuqAOeLF/DevXXFuVfvlTsfa274APyZFIBIT2WExJRKmREdItlAxH8WUk0oX3jaBT6HPGJCzn6Qgiq2LtZq79PKtn5aJjwkYFuumpbfKY2k4EE/8DakS5W3ug3GY/5AnBY+hV0QSfFP2z6xnXEOeP6p1G5zcsWsxcQb5jw+KGupueybaMIBRIPuB6kmoba2Ebk7V1pUuUFxLleB4AuOMxnVNWFE6NXIFF+h11FzIvygAsqDW7A75BXKmCvMhYOyevSHKq9KwnN6RwuE5kD5APN+Anw== Client@VM
runcmd:
  - sudo systemctl start qemu-guest-agent
  - sudo systemctl enable qemu-guest-agent
  - sudo sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sudo sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
  - echo -e 'modprobe acpiphp' | sudo tee -a /etc/modules >/dev/nul
  - echo -e 'modprobe pci_hotplug' | sudo tee -a /etc/modules >/dev/nul
  - sudo sed -i 's|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash memhp_default_state=online"|g' /etc/default/grub
  - sudo update-grub
power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  #timeout: 30
  condition: true
  #condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi
final_message: "The system is finally up, after $UPTIME seconds"
# cloud-init logs: /var/log/cloud-init.log and /var/log/cloud-init-output.log