proxmox_url          = "https://192.168.50.10:8006/api2/json"
proxmox_api_user     = "root@pam"
proxmox_api_password = "packer" // set via Enviroment Variable 
proxmox_node_name    = "one"
template_name        = "template-ubuntu-base-20-04-1-{{ isotime \"2006-01-02-T15-04-05\" }}"
template_description = "Ubuntu 20.04, generated by Packer on {{ isotime \"2006-01-02T15:04:05Z\" }}"

ssh_fullname = "packer" // set via Enviroment Variable 
ssh_password = "packer" // set via Enviroment Variable 
ssh_username = "packer" // set via Enviroment Variable 

vmid = 4000
