variable "proxmox_url" {
  type        = string
  default     = "https://192.168.50.10:8006/api2/json"
  description = "The hostname of Proxmox-VE node that will be accessed via the Web API"
  sensitive   = false
}

variable "proxmox_api_user" {
  type        = string
  default     = "root@pam"
  description = "Proxmox-VE API User that will perform the commands on the PVE host"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}

variable "proxmox_api_password" {
  type        = string
  default     = "packer" // set via Enviroment Variable 
  description = "Password of the Proxmox-VE API User that will perform the commands on the PVE host"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}

variable "proxmox_node_name" {
  type        = string
  default     = "one"
  description = "The name of the Proxmox-VE Node"
  sensitive   = false
}

variable "clone_vm_name" {
  type        = string
  default     = "ubuntu2004-cloud"
  description = "The name of the VM packer should clone and build from"
  sensitive   = false
}

variable "pool_name" {
  type        = string
  default     = ""
  description = "Name of resource pool to create virtual machine in"
  sensitive   = false
}

variable "vm_name" {
  type        = string
  default     = "ubuntu-base-20-04-1-{{ isotime \"2006-01-02-T15-04-05\" }}"
  description = "Name of the Proxmox-VE Virtual Machine during creation"
  sensitive   = false
}

variable "vm_id" {
  type        = number
  description = "The (unique) ID of the Virtual Machine that will be created to configure the template"
  sensitive   = false
}

variable "memory" {
  type        = number
  default     = 4096
  description = "Available memory on the template"
  sensitive   = false
}

variable "cores" {
  type        = number
  default     = 2
  description = "	Available cores on the template"
  sensitive   = false
}

variable "sockets" {
  type        = number
  default     = 1
  description = "Available sockets on the template"
  sensitive   = false
}

variable "cpu_type" {
  type        = string
  default     = "host"
  description = "The CPU type to emulate. Defaults to kvm64"
  sensitive   = false
}

variable "os_type" {
  type        = string
  default     = "l26"
  description = "The operating system. Defaults to other"
  sensitive   = false
}

variable "vga_type" {
  type        = string
  default     = "serial0"
  description = "Can be cirrus, none, qxl,qxl2, qxl3, qxl4, serial0, serial1, serial2, serial3, std, virtio, vmware. Defaults to std."
  sensitive   = false
}

variable "storage_pool" {
  type        = string
  default     = "local-lvm"
  description = "The data store the Virtual Machine OS disk will be created on"
  sensitive   = false
}

variable "storage_pool_type" {
  type        = string
  default     = "lvm-thin"
  description = "The type of the OS disk data store"
  sensitive   = false
}

variable "disk_size" {
  type        = string
  default     = "20G"
  description = "Operating System disk size of the template"
  sensitive   = false
}

variable "template_name" {
  type        = string
  default     = "template-ubuntu-base-20-04-1-{{ isotime \"2006-01-02-T15-04-05\" }}"
  description = "Name of the Proxmox-VE Template to be created"
  sensitive   = false
}

variable "template_description" {
  type        = string
  default     = "Ubuntu 20.04, generated by Packer on {{ isotime \"2006-01-02T15:04:05Z\" }}"
  description = "Description applied to the Proxmox-VE Template to be created"
  sensitive   = false
}

variable "ssh_username" {
  type        = string
  default     = "ubuntu"
  description = "Default username, if modified from packer update the default preseed.cfg file d-i preseed/late_command string command and update it to your new sudoer username"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}

variable "ssh_fullname" {
  type        = string
  default     = "ubuntu"
  description = "Default User Full Name"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}

variable "ssh_private_key_file" {
  type        = string
  default     = "~/.ssh/client-id_rsa"
  description = "Default User Password"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}

variable "ssh_password" {
  type        = string
  default     = "packer"
  description = "Default User Password"
  sensitive   = true
  # When a variable is sensitive all string-values from that variable will be
  # obfuscated from Packer's output.
}
